# Generated by Django 5.0.6 on 2024-06-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0003_alter_category_image_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surgicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='category_images/')),
            ],
        ),
    ]
