# Generated by Django 5.0.6 on 2024-06-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0004_surgicals'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='admin_profile_pictures/')),
                ('admin_name', models.CharField(max_length=255)),
                ('admin_address', models.TextField()),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
