# Generated by Django 5.0.6 on 2024-06-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0006_alter_adminprofile_admin_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
