# Generated by Django 5.0.6 on 2024-06-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0008_adminprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
